/**
 * collapse.js
 *
 * Facade aggregating collapse state, city/economic panel toggles, and
 * combat/GB panel toggles for FoE-Info.
 */

import { hideAllTooltips } from '../ui/collapseToggleRunner.js';
import { createLogger } from '../utils/logger.js';
import {
  fCollapseBonus,
  fCollapseBuildings,
  fCollapseClipboard,
  fCollapseCultural,
  fCollapseFriends,
  fCollapseGalaxy,
  fCollapseGoods,
  fCollapseGuild,
  fCollapseHood,
  fCollapseIncidents,
  fCollapseLists,
  fCollapseStats,
} from './cityPanelToggles.js';
import {
  collapseArmy,
  collapseBattleground,
  collapseBonus,
  collapseBuildingCost,
  collapseBuildings,
  collapseClipboard,
  collapseCultural,
  collapseDonation,
  collapseExpedition,
  collapseFriends,
  collapseGalaxy,
  collapseGBDonors,
  collapseGBGLeaderboard,
  collapseGBInfo,
  collapseGBinvest,
  collapseGBRewards,
  collapseGoods,
  collapseGuild,
  collapseHood,
  collapseIncidents,
  collapseInvested,
  collapseLists,
  collapseQIContributions,
  collapseQILeaderboard,
  collapseRewards,
  collapseStats,
  collapseTarget,
  collapseTargetGen,
  collapseTreasury,
  collapseTreasuryLog,
  setCollapse,
} from './collapseState.js';
import {
  fCollapseArmy,
  fCollapseBattleground,
  fCollapseBuildingCost,
  fCollapseDonation,
  fCollapseExpedition,
  fCollapseGBDonors,
  fCollapseGBGLeaderboard,
  fCollapseGBInfo,
  fCollapseInvested,
  fCollapseQIContributions,
  fCollapseQILeaderboard,
  fCollapseRewards,
  fCollapseTarget,
  fCollapseTargetGen,
  fCollapseTreasury,
  fCollapseTreasuryLog,
} from './combatGbToggles.js';

const logger = createLogger('Collapse');
logger.debug('Collapse facade loaded');

export {
  collapseArmy,
  collapseBattleground,
  collapseBonus,
  collapseBuildingCost,
  collapseBuildings,
  collapseClipboard,
  collapseCultural,
  collapseDonation,
  collapseExpedition,
  collapseFriends,
  collapseGBDonors,
  collapseGBGLeaderboard,
  collapseGBInfo,
  collapseGBinvest,
  collapseGBRewards,
  collapseGalaxy,
  collapseGoods,
  collapseGuild,
  collapseHood,
  collapseIncidents,
  collapseInvested,
  collapseLists,
  collapseQIContributions,
  collapseQILeaderboard,
  collapseRewards,
  collapseStats,
  collapseTarget,
  collapseTargetGen,
  collapseTreasury,
  collapseTreasuryLog,
  setCollapse,
  fCollapseFriends,
  fCollapseLists,
  fCollapseHood,
  fCollapseGalaxy,
  fCollapseGuild,
  fCollapseIncidents,
  fCollapseGoods,
  fCollapseStats,
  fCollapseBuildings,
  fCollapseBonus,
  fCollapseCultural,
  fCollapseClipboard,
  fCollapseGBInfo,
  fCollapseArmy,
  fCollapseRewards,
  fCollapseGBDonors,
  fCollapseInvested,
  fCollapseDonation,
  fCollapseBattleground,
  fCollapseBuildingCost,
  fCollapseExpedition,
  fCollapseTreasury,
  fCollapseTreasuryLog,
  fCollapseTarget,
  fCollapseTargetGen,
  fCollapseGBGLeaderboard,
  fCollapseQIContributions,
  fCollapseQILeaderboard,
  hideAllTooltips as fHideAllTooltips,
};

export default setCollapse;
