import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

const root = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '../..',
);
const FONT_DIR = path.join(root, 'src', 'fonts');
/** The pristine full-size upstream font — must exist and never be overwritten. */
const FONT_SRC = path.join(
  FONT_DIR,
  'MaterialSymbolsOutlined-Regular-full.woff2',
);
/** The subset output — generated by the script. */
const FONT = path.join(FONT_DIR, 'MaterialSymbolsOutlined-Regular.woff2');
const MANIFEST = path.join(FONT_DIR, 'icons-subset.json');
const CLASS = 'material-symbols-outlined';

function jsFiles(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...jsFiles(full));
    else if (/\.(?:js|mjs|cjs)$/.test(entry.name)) out.push(full);
  }
  return out;
}

/** Mirrors findIconNames() in scripts/subset-icons-font.mjs. */
function usedIconNames() {
  const names = new Set();
  const re = new RegExp(`${CLASS}[\\s\\S]{0,600}?>([a-z0-9_]+)<`, 'g');
  for (const file of jsFiles(path.join(root, 'src', 'js'))) {
    for (const m of fs.readFileSync(file, 'utf8').matchAll(re)) names.add(m[1]);
  }
  return [...names].sort();
}

function sha256(filePath) {
  return crypto
    .createHash('sha256')
    .update(fs.readFileSync(filePath))
    .digest('hex');
}

test('full upstream source font is committed and never overwritten', () => {
  assert.ok(
    fs.existsSync(FONT_SRC),
    `Full upstream font missing: ${path.relative(root, FONT_SRC)}. ` +
      'Run: git show a446fd4~1:src/fonts/MaterialSymbolsOutlined-Regular.woff2 > ' +
      path.relative(root, FONT_SRC),
  );

  const srcBytes = fs.statSync(FONT_SRC).size;
  // The full Material Symbols variable font is ~3.9 MB. If the file is under
  // 1 MB it is either missing or has been accidentally overwritten with a subset.
  assert.ok(
    srcBytes > 1_000_000,
    `Full source font is only ${srcBytes.toLocaleString()} bytes; ` +
      'expected >1 MB (the full upstream variable font is ~3.9 MB).',
  );
});

test('subset output is smaller than the source and ships in the extension', () => {
  const srcBytes = fs.statSync(FONT_SRC).size;
  const outBytes = fs.statSync(FONT).size;

  assert.ok(
    outBytes < srcBytes,
    `Output font (${outBytes.toLocaleString()} bytes) is not smaller than ` +
      `source (${srcBytes.toLocaleString()} bytes) — subsetting may be a no-op.`,
  );

  // The subset should be well under 200 KB (budget from the original test).
  assert.ok(
    outBytes < 200_000,
    `Subset font is ${outBytes.toLocaleString()} bytes; expected < 200 KB. ` +
      'Run npm run fonts:subset.',
  );
});

test('icons-subset manifest lists every icon used in source code', () => {
  const manifest = JSON.parse(fs.readFileSync(MANIFEST, 'utf8'));
  const used = usedIconNames();

  assert.ok(used.length > 0, 'scanner found no icons — test would be vacuous');

  const missing = used.filter((n) => !manifest.icons.includes(n));
  assert.deepEqual(
    missing,
    [],
    `icons used in src but absent from subset: ${missing.join(', ')}. ` +
      'Run npm run fonts:subset and commit the result.',
  );

  const stale = manifest.icons.filter((n) => !used.includes(n));
  assert.deepEqual(
    stale,
    [],
    `subset holds icons no longer used: ${stale.join(', ')}. Re-run npm run fonts:subset.`,
  );
});

test('manifest source field points to the full upstream font', () => {
  const manifest = JSON.parse(fs.readFileSync(MANIFEST, 'utf8'));
  assert.equal(
    manifest.source,
    'src/fonts/MaterialSymbolsOutlined-Regular-full.woff2',
    'manifest source must reference the full upstream font, not the subset output',
  );
});

test('running the subset script twice produces byte-identical output', async () => {
  // Record state before the first run.
  const srcHashBefore = sha256(FONT_SRC);

  // First run.
  execFileSync('node', ['scripts/subset-icons-font.mjs'], {
    cwd: root,
    stdio: 'pipe',
  });

  const srcHashAfter1 = sha256(FONT_SRC);
  const subsetHashAfter1 = sha256(FONT);

  // Source must not have been modified by the first run.
  assert.equal(
    srcHashAfter1,
    srcHashBefore,
    'first run modified the full upstream source font — this is the core bug',
  );

  // Second run.
  execFileSync('node', ['scripts/subset-icons-font.mjs'], {
    cwd: root,
    stdio: 'pipe',
  });

  const srcHashAfter2 = sha256(FONT_SRC);
  const subsetHashAfter2 = sha256(FONT);

  // Source must still be untouched.
  assert.equal(
    srcHashAfter2,
    srcHashBefore,
    'second run modified the full upstream source font',
  );

  // Subset output must be byte-identical across both runs.
  assert.equal(
    subsetHashAfter2,
    subsetHashAfter1,
    'subset output differs after second run — the script is not idempotent',
  );
});
